In [20]:
from sklearn.datasets import load_iris
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.model_selection import train_test_split
import graphviz
import numpy as np

In [21]:
iris = load_iris()
X = iris.data
y = iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=4)

# Gaussian

In [22]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
accuracy = gnb.score(X_test,y_test)
print(accuracy)

0.9777777777777777


# Multinomial

In [23]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
accuracy = mnb.score(X_test,y_test)
print(accuracy)

0.8666666666666667


# Bernoulli

In [24]:
bnb = BernoulliNB()
bnb.fit(X_train,y_train)
accuracy = bnb.score(X_test,y_test)
print(accuracy)

0.2222222222222222


In [28]:
print(classification_report(y_test, gnb.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.91      1.00      0.95        10
           2       1.00      0.93      0.96        14

   micro avg       0.98      0.98      0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [29]:
# C(i,j) is equal to the number of observations known to be in group i but predicted to be in group j.
print(confusion_matrix(y_test, gnb.predict(X_test)))

[[21  0  0]
 [ 0 10  0]
 [ 0  1 13]]
